programs:
  spl_stake_pool:
    program_id: "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
    instructions:
      increase_validator_stake:
        stake_pools:
          "Jito4APyf642JPZPx3hGc6WWJ8zPKtRbRs4P815Awbb":
            thresholds:
              - value: 0.1  # SOL
                notification:
                  description: "Increase validator stake detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # SOL
                notification:
                  description: "Large Increase validator stake detected"
                  destinations: ["slack"]
              - value: 5000.0  # SOL
                notification:
                  description: "Very large Increase validator stake detected"
                  destinations: ["slack"]
              - value: 10000.0  # SOL
                notification:
                  description: "Whale Increase validator stake detected"
                  destinations: ["slack"]
      deposit_stake:
        lsts:
          "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn":
            thresholds:
              - value: 0.1  # SOL
                notification:
                  description: "JitoSOL stake deposit detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # SOL
                notification:
                  description: "Large JitoSOL stake deposit detected"
                  destinations: ["slack"]
              - value: 5000.0  # SOL
                notification:
                  description: "Very large JitoSOL stake deposit detected"
                  destinations: ["slack"]
              - value: 10000.0  # SOL
                notification:
                  description: "Whale JitoSOL stake deposit detected"
                  destinations: ["slack"]
      withdraw_stake:
        lsts:
          "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn":
            thresholds:
              - value: 0.1  # SOL
                notification:
                  description: "JitoSOL stake withdrawal detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # SOL
                notification:
                  description: "Large JitoSOL stake withdrawal detected"
                  destinations: ["slack"]
              - value: 5000.0  # SOL
                notification:
                  description: "Very large JitoSOL stake withdrawal detected"
                  destinations: ["slack"]
              - value: 10000.0  # SOL
                notification:
                  description: "Whale JitoSOL stake withdrawal detected"
                  destinations: ["slack"]
      deposit_sol:
        lsts:
          "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn":
            thresholds:
              - value: 0.1  # SOL
                notification:
                  description: "SOL deposit to JitoSOL detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # SOL
                notification:
                  description: "Large SOL deposit to JitoSOL detected"
                  destinations: ["slack"]
              - value: 5000.0  # SOL
                notification:
                  description: "Very large SOL deposit to JitoSOL detected"
                  destinations: ["slack"]
              - value: 10000.0  # SOL
                notification:
                  description: "Whale SOL deposit to JitoSOL detected"
                  destinations: ["slack"]
      withdraw_sol:
        lsts:
          "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn":
            thresholds:
              - value: 0.1  # SOL
                notification:
                  description: "SOL withdrawal from JitoSOL detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # SOL
                notification:
                  description: "Large SOL withdrawal from JitoSOL detected"
                  destinations: ["slack"]
              - value: 5000.0  # SOL
                notification:
                  description: "Very large SOL withdrawal from JitoSOL detected"
                  destinations: ["slack"]
              - value: 10000.0  # SOL
                notification:
                  description: "Whale SOL withdrawal from JitoSOL detected"
                  destinations: ["slack"]
      decrease_validator_stake_with_reserve:
        stake_pools:
          "Jito4APyf642JPZPx3hGc6WWJ8zPKtRbRs4P815Awbb":
            thresholds:
              - value: 0.1  # SOL
                notification:
                  description: "Decrease validator stake with reserve detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # SOL
                notification:
                  description: "Large Decrease validator stake with reserve detected"
                  destinations: ["slack"]
              - value: 5000.0  # SOL
                notification:
                  description: "Very large Decrease validator stake with reserve detected"
                  destinations: ["slack"]
              - value: 10000.0  # SOL
                notification:
                  description: "Whale Decrease validator stake with reserve detected"
                  destinations: ["slack"]
  jito_vault:
    program_id: "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
    instructions:
      mint_to:
        vrts:
          "CXSLcb8gFEw2zhFwaQEZ2xCRpoN2dxafMNm7HuciDfDq":
            thresholds:
              - value: 0.1  # VRT
                notification:
                  description: "Mint detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # VRT
                notification:
                  description: "Large Mint detected"
                  destinations: ["telegram"]
              - value: 5000.0  # VRT
                notification:
                  description: "Very large Mint detected"
                  destinations: ["telegram", "slack"]
              - value: 10000.0  # VRT
                notification:
                  description: "Whale Mint detected"
                  destinations: ["telegram", "slack", "discord"]
          "CkXLPfDG3cDawtUvnztq99HdGoQWhJceBZxqKYL2TUrg":
            thresholds:
              - value: 0.1  # VRT
                notification:
                  description: "Mint detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # VRT
                notification:
                  description: "Large Mint detected"
                  destinations: ["telegram"]
              - value: 5000.0  # VRT
                notification:
                  description: "Very large Mint detected"
                  destinations: ["telegram", "slack"]
              - value: 10000.0  # VRT
                notification:
                  description: "Whale Mint detected"
                  destinations: ["telegram", "slack", "discord"]
      enqueue_withdrawal:
        vrts: 
          "CXSLcb8gFEw2zhFwaQEZ2xCRpoN2dxafMNm7HuciDfDq":
            thresholds:
              - value: 0.1  # VRT
                notification:
                  description: "Withdrawal detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # VRT
                notification:
                  description: "Large Withdrawal detected"
                  destinations: ["telegram"]
              - value: 5000.0  # VRT
                notification:
                  description: "Very large Withdrawal detected"
                  destinations: ["telegram", "slack"]
              - value: 10000.0  # VRT
                notification:
                  description: "Whale Withdrawal detected"
                  destinations: ["telegram", "slack", "discord"]
          "CkXLPfDG3cDawtUvnztq99HdGoQWhJceBZxqKYL2TUrg":
            thresholds:
              - value: 0.1  # VRT
                notification:
                  description: "Withdrawal detected"
                  destinations: ["slack", "twitter"]
              - value: 1000.0  # VRT
                notification:
                  description: "Large Withdrawal detected"
                  destinations: ["telegram"]
              - value: 5000.0  # VRT
                notification:
                  description: "Very large Withdrawal detected"
                  destinations: ["telegram", "slack"]
              - value: 10000.0  # VRT
                notification:
                  description: "Whale Withdrawal detected"
                  destinations: ["telegram", "slack", "discord"]
        # usd_thresholds:  # New section for USD thresholds
        #   - value: 1  # USD
        #     notification:
        #       description: "Withdrawal worth $1+ detected"
        #       destinations: ["slack"]
        #   - value: 10000  # USD
        #     notification:
        #       description: "Large Withdrawal worth $10,000+ detected"
        #       destinations: ["telegram", "slack"]
        #   - value: 100000  # USD
        #     notification:
        #       description: "Very large Withdrawal worth $100,000+ detected"
        #       destinations: ["telegram", "slack", "discord"]
  
# notifications:
#   slack:
#     webhook_url: ""
#     channel: ""
#   
#   discord:
#     webhook_url: ""
#   
#   telegram:
#     bot_token: ""
#     chat_id: ""
# 
#   twitter:
#     twitter_bearer_token: ""
#     twitter_api_key: ""
#     twitter_api_secret: ""
#     twitter_access_token: ""
#     twitter_access_token_secret: ""

explorer_url: "https://solscan.io"

message_templates:
  default: "{{description}} - Amount: {{amount}} {{currency_unit}} - Tx: https://explorer.solana.com/tx/{{tx_hash}}"
  slack: "<!here> {{description}} - Amount: {{amount}} {{currency_unit}} - <https://explorer.solana.com/tx/{{tx_hash}}|View Transaction>"
  discord: "@here {{description}} - Amount: {{amount}} {{currency_unit}} - [View Transaction](https://explorer.solana.com/tx/{{tx_hash}})"
