//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct DepositStake {
    pub stake_pool: solana_program::pubkey::Pubkey,

    pub validator_list_storage: solana_program::pubkey::Pubkey,

    pub stake_pool_deposit_authority: solana_program::pubkey::Pubkey,

    pub stake_pool_withdraw_authority: solana_program::pubkey::Pubkey,

    pub deposit_stake_address: solana_program::pubkey::Pubkey,

    pub validator_stake_account: solana_program::pubkey::Pubkey,

    pub reserve_stake_account: solana_program::pubkey::Pubkey,

    pub pool_tokens_to: solana_program::pubkey::Pubkey,

    pub manager_fee_account: solana_program::pubkey::Pubkey,

    pub referrer_pool_tokens_account: solana_program::pubkey::Pubkey,

    pub pool_mint: solana_program::pubkey::Pubkey,

    pub clock: solana_program::pubkey::Pubkey,

    pub sysvar_stake_history: solana_program::pubkey::Pubkey,

    pub token_program: solana_program::pubkey::Pubkey,

    pub stake_program: solana_program::pubkey::Pubkey,
}

impl DepositStake {
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(15 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_pool,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.validator_list_storage,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_pool_deposit_authority,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_pool_withdraw_authority,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.deposit_stake_address,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.validator_stake_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.reserve_stake_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.pool_tokens_to,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.manager_fee_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.referrer_pool_tokens_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.pool_mint,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.clock, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.sysvar_stake_history,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&DepositStakeInstructionData::new()).unwrap();

        solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DepositStakeInstructionData {
    discriminator: [u8; 8],
}

impl DepositStakeInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [160, 167, 9, 220, 74, 243, 228, 43],
        }
    }
}

impl Default for DepositStakeInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `DepositStake`.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[writable]` validator_list_storage
///   2. `[]` stake_pool_deposit_authority
///   3. `[]` stake_pool_withdraw_authority
///   4. `[writable]` deposit_stake_address
///   5. `[writable]` validator_stake_account
///   6. `[writable]` reserve_stake_account
///   7. `[writable]` pool_tokens_to
///   8. `[writable]` manager_fee_account
///   9. `[writable]` referrer_pool_tokens_account
///   10. `[writable]` pool_mint
///   11. `[]` clock
///   12. `[optional]` sysvar_stake_history (default to `SysvarStakeHistory1111111111111111111111111`)
///   13. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   14. `[]` stake_program
#[derive(Clone, Debug, Default)]
pub struct DepositStakeBuilder {
    stake_pool: Option<solana_program::pubkey::Pubkey>,
    validator_list_storage: Option<solana_program::pubkey::Pubkey>,
    stake_pool_deposit_authority: Option<solana_program::pubkey::Pubkey>,
    stake_pool_withdraw_authority: Option<solana_program::pubkey::Pubkey>,
    deposit_stake_address: Option<solana_program::pubkey::Pubkey>,
    validator_stake_account: Option<solana_program::pubkey::Pubkey>,
    reserve_stake_account: Option<solana_program::pubkey::Pubkey>,
    pool_tokens_to: Option<solana_program::pubkey::Pubkey>,
    manager_fee_account: Option<solana_program::pubkey::Pubkey>,
    referrer_pool_tokens_account: Option<solana_program::pubkey::Pubkey>,
    pool_mint: Option<solana_program::pubkey::Pubkey>,
    clock: Option<solana_program::pubkey::Pubkey>,
    sysvar_stake_history: Option<solana_program::pubkey::Pubkey>,
    token_program: Option<solana_program::pubkey::Pubkey>,
    stake_program: Option<solana_program::pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl DepositStakeBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn stake_pool(&mut self, stake_pool: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn validator_list_storage(
        &mut self,
        validator_list_storage: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.validator_list_storage = Some(validator_list_storage);
        self
    }
    #[inline(always)]
    pub fn stake_pool_deposit_authority(
        &mut self,
        stake_pool_deposit_authority: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.stake_pool_deposit_authority = Some(stake_pool_deposit_authority);
        self
    }
    #[inline(always)]
    pub fn stake_pool_withdraw_authority(
        &mut self,
        stake_pool_withdraw_authority: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.stake_pool_withdraw_authority = Some(stake_pool_withdraw_authority);
        self
    }
    #[inline(always)]
    pub fn deposit_stake_address(
        &mut self,
        deposit_stake_address: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.deposit_stake_address = Some(deposit_stake_address);
        self
    }
    #[inline(always)]
    pub fn validator_stake_account(
        &mut self,
        validator_stake_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.validator_stake_account = Some(validator_stake_account);
        self
    }
    #[inline(always)]
    pub fn reserve_stake_account(
        &mut self,
        reserve_stake_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.reserve_stake_account = Some(reserve_stake_account);
        self
    }
    #[inline(always)]
    pub fn pool_tokens_to(&mut self, pool_tokens_to: solana_program::pubkey::Pubkey) -> &mut Self {
        self.pool_tokens_to = Some(pool_tokens_to);
        self
    }
    #[inline(always)]
    pub fn manager_fee_account(
        &mut self,
        manager_fee_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.manager_fee_account = Some(manager_fee_account);
        self
    }
    #[inline(always)]
    pub fn referrer_pool_tokens_account(
        &mut self,
        referrer_pool_tokens_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.referrer_pool_tokens_account = Some(referrer_pool_tokens_account);
        self
    }
    #[inline(always)]
    pub fn pool_mint(&mut self, pool_mint: solana_program::pubkey::Pubkey) -> &mut Self {
        self.pool_mint = Some(pool_mint);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: solana_program::pubkey::Pubkey) -> &mut Self {
        self.clock = Some(clock);
        self
    }
    /// `[optional account, default to 'SysvarStakeHistory1111111111111111111111111']`
    #[inline(always)]
    pub fn sysvar_stake_history(
        &mut self,
        sysvar_stake_history: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.sysvar_stake_history = Some(sysvar_stake_history);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn stake_program(&mut self, stake_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_program = Some(stake_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = DepositStake {
            stake_pool: self.stake_pool.expect("stake_pool is not set"),
            validator_list_storage: self
                .validator_list_storage
                .expect("validator_list_storage is not set"),
            stake_pool_deposit_authority: self
                .stake_pool_deposit_authority
                .expect("stake_pool_deposit_authority is not set"),
            stake_pool_withdraw_authority: self
                .stake_pool_withdraw_authority
                .expect("stake_pool_withdraw_authority is not set"),
            deposit_stake_address: self
                .deposit_stake_address
                .expect("deposit_stake_address is not set"),
            validator_stake_account: self
                .validator_stake_account
                .expect("validator_stake_account is not set"),
            reserve_stake_account: self
                .reserve_stake_account
                .expect("reserve_stake_account is not set"),
            pool_tokens_to: self.pool_tokens_to.expect("pool_tokens_to is not set"),
            manager_fee_account: self
                .manager_fee_account
                .expect("manager_fee_account is not set"),
            referrer_pool_tokens_account: self
                .referrer_pool_tokens_account
                .expect("referrer_pool_tokens_account is not set"),
            pool_mint: self.pool_mint.expect("pool_mint is not set"),
            clock: self.clock.expect("clock is not set"),
            sysvar_stake_history: self.sysvar_stake_history.unwrap_or(solana_program::pubkey!(
                "SysvarStakeHistory1111111111111111111111111"
            )),
            token_program: self.token_program.unwrap_or(solana_program::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            stake_program: self.stake_program.expect("stake_program is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `deposit_stake` CPI accounts.
pub struct DepositStakeCpiAccounts<'a, 'b> {
    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list_storage: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_deposit_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_withdraw_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub deposit_stake_address: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub reserve_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool_tokens_to: &'b solana_program::account_info::AccountInfo<'a>,

    pub manager_fee_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub referrer_pool_tokens_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool_mint: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub sysvar_stake_history: &'b solana_program::account_info::AccountInfo<'a>,

    pub token_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `deposit_stake` CPI instruction.
pub struct DepositStakeCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list_storage: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_deposit_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_withdraw_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub deposit_stake_address: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub reserve_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool_tokens_to: &'b solana_program::account_info::AccountInfo<'a>,

    pub manager_fee_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub referrer_pool_tokens_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool_mint: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub sysvar_stake_history: &'b solana_program::account_info::AccountInfo<'a>,

    pub token_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,
}

impl<'a, 'b> DepositStakeCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: DepositStakeCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            stake_pool: accounts.stake_pool,
            validator_list_storage: accounts.validator_list_storage,
            stake_pool_deposit_authority: accounts.stake_pool_deposit_authority,
            stake_pool_withdraw_authority: accounts.stake_pool_withdraw_authority,
            deposit_stake_address: accounts.deposit_stake_address,
            validator_stake_account: accounts.validator_stake_account,
            reserve_stake_account: accounts.reserve_stake_account,
            pool_tokens_to: accounts.pool_tokens_to,
            manager_fee_account: accounts.manager_fee_account,
            referrer_pool_tokens_account: accounts.referrer_pool_tokens_account,
            pool_mint: accounts.pool_mint,
            clock: accounts.clock,
            sysvar_stake_history: accounts.sysvar_stake_history,
            token_program: accounts.token_program,
            stake_program: accounts.stake_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(15 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_pool.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.validator_list_storage.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_pool_deposit_authority.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_pool_withdraw_authority.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.deposit_stake_address.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.validator_stake_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.reserve_stake_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.pool_tokens_to.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.manager_fee_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.referrer_pool_tokens_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.pool_mint.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.clock.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.sysvar_stake_history.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&DepositStakeInstructionData::new()).unwrap();

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(16 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.stake_pool.clone());
        account_infos.push(self.validator_list_storage.clone());
        account_infos.push(self.stake_pool_deposit_authority.clone());
        account_infos.push(self.stake_pool_withdraw_authority.clone());
        account_infos.push(self.deposit_stake_address.clone());
        account_infos.push(self.validator_stake_account.clone());
        account_infos.push(self.reserve_stake_account.clone());
        account_infos.push(self.pool_tokens_to.clone());
        account_infos.push(self.manager_fee_account.clone());
        account_infos.push(self.referrer_pool_tokens_account.clone());
        account_infos.push(self.pool_mint.clone());
        account_infos.push(self.clock.clone());
        account_infos.push(self.sysvar_stake_history.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.stake_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `DepositStake` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[writable]` validator_list_storage
///   2. `[]` stake_pool_deposit_authority
///   3. `[]` stake_pool_withdraw_authority
///   4. `[writable]` deposit_stake_address
///   5. `[writable]` validator_stake_account
///   6. `[writable]` reserve_stake_account
///   7. `[writable]` pool_tokens_to
///   8. `[writable]` manager_fee_account
///   9. `[writable]` referrer_pool_tokens_account
///   10. `[writable]` pool_mint
///   11. `[]` clock
///   12. `[]` sysvar_stake_history
///   13. `[]` token_program
///   14. `[]` stake_program
#[derive(Clone, Debug)]
pub struct DepositStakeCpiBuilder<'a, 'b> {
    instruction: Box<DepositStakeCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DepositStakeCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(DepositStakeCpiBuilderInstruction {
            __program: program,
            stake_pool: None,
            validator_list_storage: None,
            stake_pool_deposit_authority: None,
            stake_pool_withdraw_authority: None,
            deposit_stake_address: None,
            validator_stake_account: None,
            reserve_stake_account: None,
            pool_tokens_to: None,
            manager_fee_account: None,
            referrer_pool_tokens_account: None,
            pool_mint: None,
            clock: None,
            sysvar_stake_history: None,
            token_program: None,
            stake_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn stake_pool(
        &mut self,
        stake_pool: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn validator_list_storage(
        &mut self,
        validator_list_storage: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.validator_list_storage = Some(validator_list_storage);
        self
    }
    #[inline(always)]
    pub fn stake_pool_deposit_authority(
        &mut self,
        stake_pool_deposit_authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool_deposit_authority = Some(stake_pool_deposit_authority);
        self
    }
    #[inline(always)]
    pub fn stake_pool_withdraw_authority(
        &mut self,
        stake_pool_withdraw_authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool_withdraw_authority = Some(stake_pool_withdraw_authority);
        self
    }
    #[inline(always)]
    pub fn deposit_stake_address(
        &mut self,
        deposit_stake_address: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.deposit_stake_address = Some(deposit_stake_address);
        self
    }
    #[inline(always)]
    pub fn validator_stake_account(
        &mut self,
        validator_stake_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.validator_stake_account = Some(validator_stake_account);
        self
    }
    #[inline(always)]
    pub fn reserve_stake_account(
        &mut self,
        reserve_stake_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.reserve_stake_account = Some(reserve_stake_account);
        self
    }
    #[inline(always)]
    pub fn pool_tokens_to(
        &mut self,
        pool_tokens_to: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_tokens_to = Some(pool_tokens_to);
        self
    }
    #[inline(always)]
    pub fn manager_fee_account(
        &mut self,
        manager_fee_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.manager_fee_account = Some(manager_fee_account);
        self
    }
    #[inline(always)]
    pub fn referrer_pool_tokens_account(
        &mut self,
        referrer_pool_tokens_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.referrer_pool_tokens_account = Some(referrer_pool_tokens_account);
        self
    }
    #[inline(always)]
    pub fn pool_mint(
        &mut self,
        pool_mint: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_mint = Some(pool_mint);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.clock = Some(clock);
        self
    }
    #[inline(always)]
    pub fn sysvar_stake_history(
        &mut self,
        sysvar_stake_history: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.sysvar_stake_history = Some(sysvar_stake_history);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn stake_program(
        &mut self,
        stake_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_program = Some(stake_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let instruction = DepositStakeCpi {
            __program: self.instruction.__program,

            stake_pool: self.instruction.stake_pool.expect("stake_pool is not set"),

            validator_list_storage: self
                .instruction
                .validator_list_storage
                .expect("validator_list_storage is not set"),

            stake_pool_deposit_authority: self
                .instruction
                .stake_pool_deposit_authority
                .expect("stake_pool_deposit_authority is not set"),

            stake_pool_withdraw_authority: self
                .instruction
                .stake_pool_withdraw_authority
                .expect("stake_pool_withdraw_authority is not set"),

            deposit_stake_address: self
                .instruction
                .deposit_stake_address
                .expect("deposit_stake_address is not set"),

            validator_stake_account: self
                .instruction
                .validator_stake_account
                .expect("validator_stake_account is not set"),

            reserve_stake_account: self
                .instruction
                .reserve_stake_account
                .expect("reserve_stake_account is not set"),

            pool_tokens_to: self
                .instruction
                .pool_tokens_to
                .expect("pool_tokens_to is not set"),

            manager_fee_account: self
                .instruction
                .manager_fee_account
                .expect("manager_fee_account is not set"),

            referrer_pool_tokens_account: self
                .instruction
                .referrer_pool_tokens_account
                .expect("referrer_pool_tokens_account is not set"),

            pool_mint: self.instruction.pool_mint.expect("pool_mint is not set"),

            clock: self.instruction.clock.expect("clock is not set"),

            sysvar_stake_history: self
                .instruction
                .sysvar_stake_history
                .expect("sysvar_stake_history is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            stake_program: self
                .instruction
                .stake_program
                .expect("stake_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct DepositStakeCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    stake_pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_list_storage: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_pool_deposit_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_pool_withdraw_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    deposit_stake_address: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_stake_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    reserve_stake_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    pool_tokens_to: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    manager_fee_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    referrer_pool_tokens_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    pool_mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    clock: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    sysvar_stake_history: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
