//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#add_validator_to_pool;
pub(crate) mod r#cleanup_removed_validator_entries;
pub(crate) mod r#create_token_metadata;
pub(crate) mod r#decrease_validator_stake;
pub(crate) mod r#deposit_sol;
pub(crate) mod r#deposit_stake;
pub(crate) mod r#increase_validator_stake;
pub(crate) mod r#initialize;
pub(crate) mod r#remove_validator_from_pool;
pub(crate) mod r#set_fee;
pub(crate) mod r#set_funding_authority;
pub(crate) mod r#set_manager;
pub(crate) mod r#set_preferred_validator;
pub(crate) mod r#set_staker;
pub(crate) mod r#update_stake_pool_balance;
pub(crate) mod r#update_token_metadata;
pub(crate) mod r#update_validator_list_balance;
pub(crate) mod r#withdraw_sol;
pub(crate) mod r#withdraw_stake;

pub use self::r#add_validator_to_pool::*;
pub use self::r#cleanup_removed_validator_entries::*;
pub use self::r#create_token_metadata::*;
pub use self::r#decrease_validator_stake::*;
pub use self::r#deposit_sol::*;
pub use self::r#deposit_stake::*;
pub use self::r#increase_validator_stake::*;
pub use self::r#initialize::*;
pub use self::r#remove_validator_from_pool::*;
pub use self::r#set_fee::*;
pub use self::r#set_funding_authority::*;
pub use self::r#set_manager::*;
pub use self::r#set_preferred_validator::*;
pub use self::r#set_staker::*;
pub use self::r#update_stake_pool_balance::*;
pub use self::r#update_token_metadata::*;
pub use self::r#update_validator_list_balance::*;
pub use self::r#withdraw_sol::*;
pub use self::r#withdraw_stake::*;
