//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct RemoveValidatorFromPool {
    pub stake_pool: solana_program::pubkey::Pubkey,

    pub staker: solana_program::pubkey::Pubkey,

    pub stake_pool_withdraw: solana_program::pubkey::Pubkey,

    pub new_stake_authority: solana_program::pubkey::Pubkey,

    pub validator_list: solana_program::pubkey::Pubkey,

    pub stake_account: solana_program::pubkey::Pubkey,

    pub transient_stake_account: solana_program::pubkey::Pubkey,

    pub destination_stake_account: solana_program::pubkey::Pubkey,

    pub clock: solana_program::pubkey::Pubkey,

    pub stake_program: solana_program::pubkey::Pubkey,
}

impl RemoveValidatorFromPool {
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_pool,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.staker,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_pool_withdraw,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.new_stake_authority,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.validator_list,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.transient_stake_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.destination_stake_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.clock, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&RemoveValidatorFromPoolInstructionData::new()).unwrap();

        solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RemoveValidatorFromPoolInstructionData {
    discriminator: [u8; 8],
}

impl RemoveValidatorFromPoolInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [161, 32, 213, 239, 221, 15, 181, 114],
        }
    }
}

impl Default for RemoveValidatorFromPoolInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `RemoveValidatorFromPool`.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[signer]` staker
///   2. `[]` stake_pool_withdraw
///   3. `[]` new_stake_authority
///   4. `[writable]` validator_list
///   5. `[writable]` stake_account
///   6. `[]` transient_stake_account
///   7. `[writable]` destination_stake_account
///   8. `[]` clock
///   9. `[]` stake_program
#[derive(Clone, Debug, Default)]
pub struct RemoveValidatorFromPoolBuilder {
    stake_pool: Option<solana_program::pubkey::Pubkey>,
    staker: Option<solana_program::pubkey::Pubkey>,
    stake_pool_withdraw: Option<solana_program::pubkey::Pubkey>,
    new_stake_authority: Option<solana_program::pubkey::Pubkey>,
    validator_list: Option<solana_program::pubkey::Pubkey>,
    stake_account: Option<solana_program::pubkey::Pubkey>,
    transient_stake_account: Option<solana_program::pubkey::Pubkey>,
    destination_stake_account: Option<solana_program::pubkey::Pubkey>,
    clock: Option<solana_program::pubkey::Pubkey>,
    stake_program: Option<solana_program::pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl RemoveValidatorFromPoolBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn stake_pool(&mut self, stake_pool: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn staker(&mut self, staker: solana_program::pubkey::Pubkey) -> &mut Self {
        self.staker = Some(staker);
        self
    }
    #[inline(always)]
    pub fn stake_pool_withdraw(
        &mut self,
        stake_pool_withdraw: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.stake_pool_withdraw = Some(stake_pool_withdraw);
        self
    }
    #[inline(always)]
    pub fn new_stake_authority(
        &mut self,
        new_stake_authority: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.new_stake_authority = Some(new_stake_authority);
        self
    }
    #[inline(always)]
    pub fn validator_list(&mut self, validator_list: solana_program::pubkey::Pubkey) -> &mut Self {
        self.validator_list = Some(validator_list);
        self
    }
    #[inline(always)]
    pub fn stake_account(&mut self, stake_account: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_account = Some(stake_account);
        self
    }
    #[inline(always)]
    pub fn transient_stake_account(
        &mut self,
        transient_stake_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.transient_stake_account = Some(transient_stake_account);
        self
    }
    #[inline(always)]
    pub fn destination_stake_account(
        &mut self,
        destination_stake_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.destination_stake_account = Some(destination_stake_account);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: solana_program::pubkey::Pubkey) -> &mut Self {
        self.clock = Some(clock);
        self
    }
    #[inline(always)]
    pub fn stake_program(&mut self, stake_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_program = Some(stake_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = RemoveValidatorFromPool {
            stake_pool: self.stake_pool.expect("stake_pool is not set"),
            staker: self.staker.expect("staker is not set"),
            stake_pool_withdraw: self
                .stake_pool_withdraw
                .expect("stake_pool_withdraw is not set"),
            new_stake_authority: self
                .new_stake_authority
                .expect("new_stake_authority is not set"),
            validator_list: self.validator_list.expect("validator_list is not set"),
            stake_account: self.stake_account.expect("stake_account is not set"),
            transient_stake_account: self
                .transient_stake_account
                .expect("transient_stake_account is not set"),
            destination_stake_account: self
                .destination_stake_account
                .expect("destination_stake_account is not set"),
            clock: self.clock.expect("clock is not set"),
            stake_program: self.stake_program.expect("stake_program is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `remove_validator_from_pool` CPI accounts.
pub struct RemoveValidatorFromPoolCpiAccounts<'a, 'b> {
    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub staker: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_withdraw: &'b solana_program::account_info::AccountInfo<'a>,

    pub new_stake_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub transient_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub destination_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `remove_validator_from_pool` CPI instruction.
pub struct RemoveValidatorFromPoolCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub staker: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_withdraw: &'b solana_program::account_info::AccountInfo<'a>,

    pub new_stake_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub transient_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub destination_stake_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,
}

impl<'a, 'b> RemoveValidatorFromPoolCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: RemoveValidatorFromPoolCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            stake_pool: accounts.stake_pool,
            staker: accounts.staker,
            stake_pool_withdraw: accounts.stake_pool_withdraw,
            new_stake_authority: accounts.new_stake_authority,
            validator_list: accounts.validator_list,
            stake_account: accounts.stake_account,
            transient_stake_account: accounts.transient_stake_account,
            destination_stake_account: accounts.destination_stake_account,
            clock: accounts.clock,
            stake_program: accounts.stake_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(10 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_pool.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.staker.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_pool_withdraw.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.new_stake_authority.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.validator_list.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.transient_stake_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.destination_stake_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.clock.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&RemoveValidatorFromPoolInstructionData::new()).unwrap();

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(11 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.stake_pool.clone());
        account_infos.push(self.staker.clone());
        account_infos.push(self.stake_pool_withdraw.clone());
        account_infos.push(self.new_stake_authority.clone());
        account_infos.push(self.validator_list.clone());
        account_infos.push(self.stake_account.clone());
        account_infos.push(self.transient_stake_account.clone());
        account_infos.push(self.destination_stake_account.clone());
        account_infos.push(self.clock.clone());
        account_infos.push(self.stake_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `RemoveValidatorFromPool` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[signer]` staker
///   2. `[]` stake_pool_withdraw
///   3. `[]` new_stake_authority
///   4. `[writable]` validator_list
///   5. `[writable]` stake_account
///   6. `[]` transient_stake_account
///   7. `[writable]` destination_stake_account
///   8. `[]` clock
///   9. `[]` stake_program
#[derive(Clone, Debug)]
pub struct RemoveValidatorFromPoolCpiBuilder<'a, 'b> {
    instruction: Box<RemoveValidatorFromPoolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RemoveValidatorFromPoolCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(RemoveValidatorFromPoolCpiBuilderInstruction {
            __program: program,
            stake_pool: None,
            staker: None,
            stake_pool_withdraw: None,
            new_stake_authority: None,
            validator_list: None,
            stake_account: None,
            transient_stake_account: None,
            destination_stake_account: None,
            clock: None,
            stake_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn stake_pool(
        &mut self,
        stake_pool: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn staker(
        &mut self,
        staker: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.staker = Some(staker);
        self
    }
    #[inline(always)]
    pub fn stake_pool_withdraw(
        &mut self,
        stake_pool_withdraw: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool_withdraw = Some(stake_pool_withdraw);
        self
    }
    #[inline(always)]
    pub fn new_stake_authority(
        &mut self,
        new_stake_authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.new_stake_authority = Some(new_stake_authority);
        self
    }
    #[inline(always)]
    pub fn validator_list(
        &mut self,
        validator_list: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.validator_list = Some(validator_list);
        self
    }
    #[inline(always)]
    pub fn stake_account(
        &mut self,
        stake_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_account = Some(stake_account);
        self
    }
    #[inline(always)]
    pub fn transient_stake_account(
        &mut self,
        transient_stake_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.transient_stake_account = Some(transient_stake_account);
        self
    }
    #[inline(always)]
    pub fn destination_stake_account(
        &mut self,
        destination_stake_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.destination_stake_account = Some(destination_stake_account);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.clock = Some(clock);
        self
    }
    #[inline(always)]
    pub fn stake_program(
        &mut self,
        stake_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_program = Some(stake_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let instruction = RemoveValidatorFromPoolCpi {
            __program: self.instruction.__program,

            stake_pool: self.instruction.stake_pool.expect("stake_pool is not set"),

            staker: self.instruction.staker.expect("staker is not set"),

            stake_pool_withdraw: self
                .instruction
                .stake_pool_withdraw
                .expect("stake_pool_withdraw is not set"),

            new_stake_authority: self
                .instruction
                .new_stake_authority
                .expect("new_stake_authority is not set"),

            validator_list: self
                .instruction
                .validator_list
                .expect("validator_list is not set"),

            stake_account: self
                .instruction
                .stake_account
                .expect("stake_account is not set"),

            transient_stake_account: self
                .instruction
                .transient_stake_account
                .expect("transient_stake_account is not set"),

            destination_stake_account: self
                .instruction
                .destination_stake_account
                .expect("destination_stake_account is not set"),

            clock: self.instruction.clock.expect("clock is not set"),

            stake_program: self
                .instruction
                .stake_program
                .expect("stake_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct RemoveValidatorFromPoolCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    stake_pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    staker: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_pool_withdraw: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    new_stake_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_list: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    transient_stake_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    destination_stake_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    clock: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
