//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::types::PreferredValidatorType;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_program::pubkey::Pubkey;

/// Accounts.
#[derive(Debug)]
pub struct SetPreferredValidator {
    pub stake_pool_address: solana_program::pubkey::Pubkey,

    pub staker: solana_program::pubkey::Pubkey,

    pub validator_list_address: solana_program::pubkey::Pubkey,
}

impl SetPreferredValidator {
    pub fn instruction(
        &self,
        args: SetPreferredValidatorInstructionArgs,
    ) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: SetPreferredValidatorInstructionArgs,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_pool_address,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.staker,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.validator_list_address,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&SetPreferredValidatorInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetPreferredValidatorInstructionData {
    discriminator: [u8; 8],
}

impl SetPreferredValidatorInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [114, 42, 19, 98, 212, 97, 109, 13],
        }
    }
}

impl Default for SetPreferredValidatorInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetPreferredValidatorInstructionArgs {
    pub validator_type: PreferredValidatorType,
    pub validator_vote_address: Option<Pubkey>,
}

/// Instruction builder for `SetPreferredValidator`.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool_address
///   1. `[signer]` staker
///   2. `[]` validator_list_address
#[derive(Clone, Debug, Default)]
pub struct SetPreferredValidatorBuilder {
    stake_pool_address: Option<solana_program::pubkey::Pubkey>,
    staker: Option<solana_program::pubkey::Pubkey>,
    validator_list_address: Option<solana_program::pubkey::Pubkey>,
    validator_type: Option<PreferredValidatorType>,
    validator_vote_address: Option<Pubkey>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl SetPreferredValidatorBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn stake_pool_address(
        &mut self,
        stake_pool_address: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.stake_pool_address = Some(stake_pool_address);
        self
    }
    #[inline(always)]
    pub fn staker(&mut self, staker: solana_program::pubkey::Pubkey) -> &mut Self {
        self.staker = Some(staker);
        self
    }
    #[inline(always)]
    pub fn validator_list_address(
        &mut self,
        validator_list_address: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.validator_list_address = Some(validator_list_address);
        self
    }
    #[inline(always)]
    pub fn validator_type(&mut self, validator_type: PreferredValidatorType) -> &mut Self {
        self.validator_type = Some(validator_type);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn validator_vote_address(&mut self, validator_vote_address: Pubkey) -> &mut Self {
        self.validator_vote_address = Some(validator_vote_address);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = SetPreferredValidator {
            stake_pool_address: self
                .stake_pool_address
                .expect("stake_pool_address is not set"),
            staker: self.staker.expect("staker is not set"),
            validator_list_address: self
                .validator_list_address
                .expect("validator_list_address is not set"),
        };
        let args = SetPreferredValidatorInstructionArgs {
            validator_type: self
                .validator_type
                .clone()
                .expect("validator_type is not set"),
            validator_vote_address: self.validator_vote_address.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `set_preferred_validator` CPI accounts.
pub struct SetPreferredValidatorCpiAccounts<'a, 'b> {
    pub stake_pool_address: &'b solana_program::account_info::AccountInfo<'a>,

    pub staker: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list_address: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `set_preferred_validator` CPI instruction.
pub struct SetPreferredValidatorCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_address: &'b solana_program::account_info::AccountInfo<'a>,

    pub staker: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list_address: &'b solana_program::account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: SetPreferredValidatorInstructionArgs,
}

impl<'a, 'b> SetPreferredValidatorCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: SetPreferredValidatorCpiAccounts<'a, 'b>,
        args: SetPreferredValidatorInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            stake_pool_address: accounts.stake_pool_address,
            staker: accounts.staker,
            validator_list_address: accounts.validator_list_address,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_pool_address.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.staker.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.validator_list_address.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&SetPreferredValidatorInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.stake_pool_address.clone());
        account_infos.push(self.staker.clone());
        account_infos.push(self.validator_list_address.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SetPreferredValidator` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool_address
///   1. `[signer]` staker
///   2. `[]` validator_list_address
#[derive(Clone, Debug)]
pub struct SetPreferredValidatorCpiBuilder<'a, 'b> {
    instruction: Box<SetPreferredValidatorCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SetPreferredValidatorCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SetPreferredValidatorCpiBuilderInstruction {
            __program: program,
            stake_pool_address: None,
            staker: None,
            validator_list_address: None,
            validator_type: None,
            validator_vote_address: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn stake_pool_address(
        &mut self,
        stake_pool_address: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool_address = Some(stake_pool_address);
        self
    }
    #[inline(always)]
    pub fn staker(
        &mut self,
        staker: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.staker = Some(staker);
        self
    }
    #[inline(always)]
    pub fn validator_list_address(
        &mut self,
        validator_list_address: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.validator_list_address = Some(validator_list_address);
        self
    }
    #[inline(always)]
    pub fn validator_type(&mut self, validator_type: PreferredValidatorType) -> &mut Self {
        self.instruction.validator_type = Some(validator_type);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn validator_vote_address(&mut self, validator_vote_address: Pubkey) -> &mut Self {
        self.instruction.validator_vote_address = Some(validator_vote_address);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let args = SetPreferredValidatorInstructionArgs {
            validator_type: self
                .instruction
                .validator_type
                .clone()
                .expect("validator_type is not set"),
            validator_vote_address: self.instruction.validator_vote_address.clone(),
        };
        let instruction = SetPreferredValidatorCpi {
            __program: self.instruction.__program,

            stake_pool_address: self
                .instruction
                .stake_pool_address
                .expect("stake_pool_address is not set"),

            staker: self.instruction.staker.expect("staker is not set"),

            validator_list_address: self
                .instruction
                .validator_list_address
                .expect("validator_list_address is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SetPreferredValidatorCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    stake_pool_address: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    staker: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_list_address: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_type: Option<PreferredValidatorType>,
    validator_vote_address: Option<Pubkey>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
