//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct SetManager {
    pub stake_pool: solana_program::pubkey::Pubkey,

    pub manager: solana_program::pubkey::Pubkey,

    pub new_manager: solana_program::pubkey::Pubkey,

    pub new_fee_receiver: solana_program::pubkey::Pubkey,
}

impl SetManager {
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_pool,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.manager,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.new_manager,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.new_fee_receiver,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&SetManagerInstructionData::new()).unwrap();

        solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetManagerInstructionData {
    discriminator: [u8; 8],
}

impl SetManagerInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [30, 197, 171, 92, 121, 184, 151, 165],
        }
    }
}

impl Default for SetManagerInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `SetManager`.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[signer]` manager
///   2. `[signer]` new_manager
///   3. `[]` new_fee_receiver
#[derive(Clone, Debug, Default)]
pub struct SetManagerBuilder {
    stake_pool: Option<solana_program::pubkey::Pubkey>,
    manager: Option<solana_program::pubkey::Pubkey>,
    new_manager: Option<solana_program::pubkey::Pubkey>,
    new_fee_receiver: Option<solana_program::pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl SetManagerBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn stake_pool(&mut self, stake_pool: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn manager(&mut self, manager: solana_program::pubkey::Pubkey) -> &mut Self {
        self.manager = Some(manager);
        self
    }
    #[inline(always)]
    pub fn new_manager(&mut self, new_manager: solana_program::pubkey::Pubkey) -> &mut Self {
        self.new_manager = Some(new_manager);
        self
    }
    #[inline(always)]
    pub fn new_fee_receiver(
        &mut self,
        new_fee_receiver: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.new_fee_receiver = Some(new_fee_receiver);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = SetManager {
            stake_pool: self.stake_pool.expect("stake_pool is not set"),
            manager: self.manager.expect("manager is not set"),
            new_manager: self.new_manager.expect("new_manager is not set"),
            new_fee_receiver: self.new_fee_receiver.expect("new_fee_receiver is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `set_manager` CPI accounts.
pub struct SetManagerCpiAccounts<'a, 'b> {
    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub manager: &'b solana_program::account_info::AccountInfo<'a>,

    pub new_manager: &'b solana_program::account_info::AccountInfo<'a>,

    pub new_fee_receiver: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `set_manager` CPI instruction.
pub struct SetManagerCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub manager: &'b solana_program::account_info::AccountInfo<'a>,

    pub new_manager: &'b solana_program::account_info::AccountInfo<'a>,

    pub new_fee_receiver: &'b solana_program::account_info::AccountInfo<'a>,
}

impl<'a, 'b> SetManagerCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: SetManagerCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            stake_pool: accounts.stake_pool,
            manager: accounts.manager,
            new_manager: accounts.new_manager,
            new_fee_receiver: accounts.new_fee_receiver,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(4 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_pool.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.manager.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.new_manager.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.new_fee_receiver.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&SetManagerInstructionData::new()).unwrap();

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(5 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.stake_pool.clone());
        account_infos.push(self.manager.clone());
        account_infos.push(self.new_manager.clone());
        account_infos.push(self.new_fee_receiver.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SetManager` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[signer]` manager
///   2. `[signer]` new_manager
///   3. `[]` new_fee_receiver
#[derive(Clone, Debug)]
pub struct SetManagerCpiBuilder<'a, 'b> {
    instruction: Box<SetManagerCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SetManagerCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SetManagerCpiBuilderInstruction {
            __program: program,
            stake_pool: None,
            manager: None,
            new_manager: None,
            new_fee_receiver: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn stake_pool(
        &mut self,
        stake_pool: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn manager(
        &mut self,
        manager: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.manager = Some(manager);
        self
    }
    #[inline(always)]
    pub fn new_manager(
        &mut self,
        new_manager: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.new_manager = Some(new_manager);
        self
    }
    #[inline(always)]
    pub fn new_fee_receiver(
        &mut self,
        new_fee_receiver: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.new_fee_receiver = Some(new_fee_receiver);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let instruction = SetManagerCpi {
            __program: self.instruction.__program,

            stake_pool: self.instruction.stake_pool.expect("stake_pool is not set"),

            manager: self.instruction.manager.expect("manager is not set"),

            new_manager: self
                .instruction
                .new_manager
                .expect("new_manager is not set"),

            new_fee_receiver: self
                .instruction
                .new_fee_receiver
                .expect("new_fee_receiver is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SetManagerCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    stake_pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    manager: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    new_manager: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    new_fee_receiver: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
