//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct WithdrawStake {
    pub stake_pool: solana_program::pubkey::Pubkey,

    pub validator_list_storage: solana_program::pubkey::Pubkey,

    pub stake_pool_withdraw: solana_program::pubkey::Pubkey,

    pub stake_to_split: solana_program::pubkey::Pubkey,

    pub stake_to_receive: solana_program::pubkey::Pubkey,

    pub user_stake_authority: solana_program::pubkey::Pubkey,

    pub user_transfer_authority: solana_program::pubkey::Pubkey,

    pub user_pool_token_account: solana_program::pubkey::Pubkey,

    pub manager_fee_account: solana_program::pubkey::Pubkey,

    pub pool_mint: solana_program::pubkey::Pubkey,

    pub clock: solana_program::pubkey::Pubkey,

    pub token_program: solana_program::pubkey::Pubkey,

    pub stake_program: solana_program::pubkey::Pubkey,
}

impl WithdrawStake {
    pub fn instruction(
        &self,
        args: WithdrawStakeInstructionArgs,
    ) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: WithdrawStakeInstructionArgs,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(13 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_pool,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.validator_list_storage,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_pool_withdraw,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_to_split,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.stake_to_receive,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.user_stake_authority,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.user_transfer_authority,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.user_pool_token_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.manager_fee_account,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.pool_mint,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.clock, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.stake_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&WithdrawStakeInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawStakeInstructionData {
    discriminator: [u8; 8],
}

impl WithdrawStakeInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [153, 8, 22, 138, 105, 176, 87, 66],
        }
    }
}

impl Default for WithdrawStakeInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawStakeInstructionArgs {
    pub arg: u64,
}

/// Instruction builder for `WithdrawStake`.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[writable]` validator_list_storage
///   2. `[]` stake_pool_withdraw
///   3. `[writable]` stake_to_split
///   4. `[writable]` stake_to_receive
///   5. `[]` user_stake_authority
///   6. `[signer]` user_transfer_authority
///   7. `[writable]` user_pool_token_account
///   8. `[writable]` manager_fee_account
///   9. `[writable]` pool_mint
///   10. `[]` clock
///   11. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   12. `[]` stake_program
#[derive(Clone, Debug, Default)]
pub struct WithdrawStakeBuilder {
    stake_pool: Option<solana_program::pubkey::Pubkey>,
    validator_list_storage: Option<solana_program::pubkey::Pubkey>,
    stake_pool_withdraw: Option<solana_program::pubkey::Pubkey>,
    stake_to_split: Option<solana_program::pubkey::Pubkey>,
    stake_to_receive: Option<solana_program::pubkey::Pubkey>,
    user_stake_authority: Option<solana_program::pubkey::Pubkey>,
    user_transfer_authority: Option<solana_program::pubkey::Pubkey>,
    user_pool_token_account: Option<solana_program::pubkey::Pubkey>,
    manager_fee_account: Option<solana_program::pubkey::Pubkey>,
    pool_mint: Option<solana_program::pubkey::Pubkey>,
    clock: Option<solana_program::pubkey::Pubkey>,
    token_program: Option<solana_program::pubkey::Pubkey>,
    stake_program: Option<solana_program::pubkey::Pubkey>,
    arg: Option<u64>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl WithdrawStakeBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn stake_pool(&mut self, stake_pool: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn validator_list_storage(
        &mut self,
        validator_list_storage: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.validator_list_storage = Some(validator_list_storage);
        self
    }
    #[inline(always)]
    pub fn stake_pool_withdraw(
        &mut self,
        stake_pool_withdraw: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.stake_pool_withdraw = Some(stake_pool_withdraw);
        self
    }
    #[inline(always)]
    pub fn stake_to_split(&mut self, stake_to_split: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_to_split = Some(stake_to_split);
        self
    }
    #[inline(always)]
    pub fn stake_to_receive(
        &mut self,
        stake_to_receive: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.stake_to_receive = Some(stake_to_receive);
        self
    }
    #[inline(always)]
    pub fn user_stake_authority(
        &mut self,
        user_stake_authority: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.user_stake_authority = Some(user_stake_authority);
        self
    }
    #[inline(always)]
    pub fn user_transfer_authority(
        &mut self,
        user_transfer_authority: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.user_transfer_authority = Some(user_transfer_authority);
        self
    }
    #[inline(always)]
    pub fn user_pool_token_account(
        &mut self,
        user_pool_token_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.user_pool_token_account = Some(user_pool_token_account);
        self
    }
    #[inline(always)]
    pub fn manager_fee_account(
        &mut self,
        manager_fee_account: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.manager_fee_account = Some(manager_fee_account);
        self
    }
    #[inline(always)]
    pub fn pool_mint(&mut self, pool_mint: solana_program::pubkey::Pubkey) -> &mut Self {
        self.pool_mint = Some(pool_mint);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: solana_program::pubkey::Pubkey) -> &mut Self {
        self.clock = Some(clock);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn stake_program(&mut self, stake_program: solana_program::pubkey::Pubkey) -> &mut Self {
        self.stake_program = Some(stake_program);
        self
    }
    #[inline(always)]
    pub fn arg(&mut self, arg: u64) -> &mut Self {
        self.arg = Some(arg);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = WithdrawStake {
            stake_pool: self.stake_pool.expect("stake_pool is not set"),
            validator_list_storage: self
                .validator_list_storage
                .expect("validator_list_storage is not set"),
            stake_pool_withdraw: self
                .stake_pool_withdraw
                .expect("stake_pool_withdraw is not set"),
            stake_to_split: self.stake_to_split.expect("stake_to_split is not set"),
            stake_to_receive: self.stake_to_receive.expect("stake_to_receive is not set"),
            user_stake_authority: self
                .user_stake_authority
                .expect("user_stake_authority is not set"),
            user_transfer_authority: self
                .user_transfer_authority
                .expect("user_transfer_authority is not set"),
            user_pool_token_account: self
                .user_pool_token_account
                .expect("user_pool_token_account is not set"),
            manager_fee_account: self
                .manager_fee_account
                .expect("manager_fee_account is not set"),
            pool_mint: self.pool_mint.expect("pool_mint is not set"),
            clock: self.clock.expect("clock is not set"),
            token_program: self.token_program.unwrap_or(solana_program::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            stake_program: self.stake_program.expect("stake_program is not set"),
        };
        let args = WithdrawStakeInstructionArgs {
            arg: self.arg.clone().expect("arg is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `withdraw_stake` CPI accounts.
pub struct WithdrawStakeCpiAccounts<'a, 'b> {
    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list_storage: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_withdraw: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_to_split: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_to_receive: &'b solana_program::account_info::AccountInfo<'a>,

    pub user_stake_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub user_transfer_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub user_pool_token_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub manager_fee_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool_mint: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub token_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `withdraw_stake` CPI instruction.
pub struct WithdrawStakeCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool: &'b solana_program::account_info::AccountInfo<'a>,

    pub validator_list_storage: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_pool_withdraw: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_to_split: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_to_receive: &'b solana_program::account_info::AccountInfo<'a>,

    pub user_stake_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub user_transfer_authority: &'b solana_program::account_info::AccountInfo<'a>,

    pub user_pool_token_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub manager_fee_account: &'b solana_program::account_info::AccountInfo<'a>,

    pub pool_mint: &'b solana_program::account_info::AccountInfo<'a>,

    pub clock: &'b solana_program::account_info::AccountInfo<'a>,

    pub token_program: &'b solana_program::account_info::AccountInfo<'a>,

    pub stake_program: &'b solana_program::account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: WithdrawStakeInstructionArgs,
}

impl<'a, 'b> WithdrawStakeCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: WithdrawStakeCpiAccounts<'a, 'b>,
        args: WithdrawStakeInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            stake_pool: accounts.stake_pool,
            validator_list_storage: accounts.validator_list_storage,
            stake_pool_withdraw: accounts.stake_pool_withdraw,
            stake_to_split: accounts.stake_to_split,
            stake_to_receive: accounts.stake_to_receive,
            user_stake_authority: accounts.user_stake_authority,
            user_transfer_authority: accounts.user_transfer_authority,
            user_pool_token_account: accounts.user_pool_token_account,
            manager_fee_account: accounts.manager_fee_account,
            pool_mint: accounts.pool_mint,
            clock: accounts.clock,
            token_program: accounts.token_program,
            stake_program: accounts.stake_program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(13 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_pool.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.validator_list_storage.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_pool_withdraw.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_to_split.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.stake_to_receive.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.user_stake_authority.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.user_transfer_authority.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.user_pool_token_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.manager_fee_account.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.pool_mint.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.clock.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.stake_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&WithdrawStakeInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SPL_STAKE_POOL_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(14 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.stake_pool.clone());
        account_infos.push(self.validator_list_storage.clone());
        account_infos.push(self.stake_pool_withdraw.clone());
        account_infos.push(self.stake_to_split.clone());
        account_infos.push(self.stake_to_receive.clone());
        account_infos.push(self.user_stake_authority.clone());
        account_infos.push(self.user_transfer_authority.clone());
        account_infos.push(self.user_pool_token_account.clone());
        account_infos.push(self.manager_fee_account.clone());
        account_infos.push(self.pool_mint.clone());
        account_infos.push(self.clock.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.stake_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `WithdrawStake` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` stake_pool
///   1. `[writable]` validator_list_storage
///   2. `[]` stake_pool_withdraw
///   3. `[writable]` stake_to_split
///   4. `[writable]` stake_to_receive
///   5. `[]` user_stake_authority
///   6. `[signer]` user_transfer_authority
///   7. `[writable]` user_pool_token_account
///   8. `[writable]` manager_fee_account
///   9. `[writable]` pool_mint
///   10. `[]` clock
///   11. `[]` token_program
///   12. `[]` stake_program
#[derive(Clone, Debug)]
pub struct WithdrawStakeCpiBuilder<'a, 'b> {
    instruction: Box<WithdrawStakeCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> WithdrawStakeCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(WithdrawStakeCpiBuilderInstruction {
            __program: program,
            stake_pool: None,
            validator_list_storage: None,
            stake_pool_withdraw: None,
            stake_to_split: None,
            stake_to_receive: None,
            user_stake_authority: None,
            user_transfer_authority: None,
            user_pool_token_account: None,
            manager_fee_account: None,
            pool_mint: None,
            clock: None,
            token_program: None,
            stake_program: None,
            arg: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn stake_pool(
        &mut self,
        stake_pool: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool = Some(stake_pool);
        self
    }
    #[inline(always)]
    pub fn validator_list_storage(
        &mut self,
        validator_list_storage: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.validator_list_storage = Some(validator_list_storage);
        self
    }
    #[inline(always)]
    pub fn stake_pool_withdraw(
        &mut self,
        stake_pool_withdraw: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_pool_withdraw = Some(stake_pool_withdraw);
        self
    }
    #[inline(always)]
    pub fn stake_to_split(
        &mut self,
        stake_to_split: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_to_split = Some(stake_to_split);
        self
    }
    #[inline(always)]
    pub fn stake_to_receive(
        &mut self,
        stake_to_receive: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_to_receive = Some(stake_to_receive);
        self
    }
    #[inline(always)]
    pub fn user_stake_authority(
        &mut self,
        user_stake_authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.user_stake_authority = Some(user_stake_authority);
        self
    }
    #[inline(always)]
    pub fn user_transfer_authority(
        &mut self,
        user_transfer_authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.user_transfer_authority = Some(user_transfer_authority);
        self
    }
    #[inline(always)]
    pub fn user_pool_token_account(
        &mut self,
        user_pool_token_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.user_pool_token_account = Some(user_pool_token_account);
        self
    }
    #[inline(always)]
    pub fn manager_fee_account(
        &mut self,
        manager_fee_account: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.manager_fee_account = Some(manager_fee_account);
        self
    }
    #[inline(always)]
    pub fn pool_mint(
        &mut self,
        pool_mint: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_mint = Some(pool_mint);
        self
    }
    #[inline(always)]
    pub fn clock(&mut self, clock: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.clock = Some(clock);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn stake_program(
        &mut self,
        stake_program: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.stake_program = Some(stake_program);
        self
    }
    #[inline(always)]
    pub fn arg(&mut self, arg: u64) -> &mut Self {
        self.instruction.arg = Some(arg);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let args = WithdrawStakeInstructionArgs {
            arg: self.instruction.arg.clone().expect("arg is not set"),
        };
        let instruction = WithdrawStakeCpi {
            __program: self.instruction.__program,

            stake_pool: self.instruction.stake_pool.expect("stake_pool is not set"),

            validator_list_storage: self
                .instruction
                .validator_list_storage
                .expect("validator_list_storage is not set"),

            stake_pool_withdraw: self
                .instruction
                .stake_pool_withdraw
                .expect("stake_pool_withdraw is not set"),

            stake_to_split: self
                .instruction
                .stake_to_split
                .expect("stake_to_split is not set"),

            stake_to_receive: self
                .instruction
                .stake_to_receive
                .expect("stake_to_receive is not set"),

            user_stake_authority: self
                .instruction
                .user_stake_authority
                .expect("user_stake_authority is not set"),

            user_transfer_authority: self
                .instruction
                .user_transfer_authority
                .expect("user_transfer_authority is not set"),

            user_pool_token_account: self
                .instruction
                .user_pool_token_account
                .expect("user_pool_token_account is not set"),

            manager_fee_account: self
                .instruction
                .manager_fee_account
                .expect("manager_fee_account is not set"),

            pool_mint: self.instruction.pool_mint.expect("pool_mint is not set"),

            clock: self.instruction.clock.expect("clock is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            stake_program: self
                .instruction
                .stake_program
                .expect("stake_program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct WithdrawStakeCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    stake_pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    validator_list_storage: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_pool_withdraw: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_to_split: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_to_receive: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    user_stake_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    user_transfer_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    user_pool_token_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    manager_fee_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    pool_mint: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    clock: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    stake_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    arg: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
